### ISSUE TITLE
Split on selectors not rules

### ISSUE THREAD

**Issue by benatwork99** [gabrysbiz/css-splitter-maven-plugin#1]
Hi,

Great plugin!

One thought, it appears to be splitting on the number of rules in the file. The IE9 (and less) issue where if you have large CSS files appears to be based on the number of selectors, not rules.

Reference: http://stackoverflow.com/a/9906889/1666041

I think if the plugin worked on selectors (or had an option to work that way) it would be more useful for this issue.

Thanks,

**Comment by agabrys** [comment]
Hi,
I'm confused, because some of the topics contain information about the maximum number of selectors and others of rules (second comment of this topic is very interesting: http://blogs.msdn.com/b/ieinternals/archive/2011/05/14/10164546.aspx).

I will add `maxSelectors` option.

This plugin is still under development so maybe I will remove `maxRules`.

Thank you for your feedback.
Regards

**Comment by agabrys** [comment]
Today I added first version with `maxSelectors` parameter (`maxRules` has been removed).

**Comment by agabrys** [comment]
I know that is a problem with "forever recursion" when split invalid CSS. I will correct it in this week. If you have a problem, then you can use older version:

```xml
<plugin>
    <groupId>biz.gabrys.maven.plugins</groupId>
    <artifactId>css-splitter-maven-plugin</artifactId>
    <version>1.0-20150917.163034-23</version>
    <configuration>
        ...
    </configuration>
</plugin>
```

**Comment by agabrys** [comment]
I uploaded a new snapshot. You can test now.

**Comment by agabrys** [comment]
I uploaded a new snapshot which split by "rules", not selectors. But this is what we want :-)

How browsers work:
```
div, ol.abc > p {
    width: 200px;
}
```
The CSS code:
* contains 2 selectors: `div` and `ol.abc > p`
* contains 1 rule: `div, ol.abc > p { width: 200px; }`

```
div {
    width: 200px;
    height: 100px;
}
```
The CSS code:
* contains 1 selector: `div`
* contains 2 rules: `div { width: 200px; }` and `div { height: 100px; }`
