### ISSUE TITLE
Special character sequences are interpreted instead of copied as is

### ISSUE THREAD

**Issue by agabrys** [gabrysbiz/css-splitter-maven-plugin#26]
Special character sequences are interpreted instead of copied, for example this selector:

    .v-ie .base .v-inline-datefield-button:after {
      content: "\200B";
    }

turns into this after spliting:

    .v-ie .base .v-inline-datefield-button:after {
      content:"​"
    }

**Comment by agabrys** [comment]
This problem is caused by CSS Parser, see: [#85 Character escape sequences gets corrupted by the parser](https://sourceforge.net/p/cssparser/bugs/85/)

**Comment by agabrys** [comment]
The fix is ready. I'm waiting for the CSS Parser 0.9.25 release.

**Comment by agabrys** [comment]
@Smasherr I see that you added `CssFormat` in more places. I'll do the same thing.

**Comment by Smasherr** [comment]
@agabrys I figured out that StylePropertyConverter is crucial to modify. I'll create a PR so you can have a look at the all changes at once.

**Comment by Smasherr** [comment]
@agabrys I'm not sure though, if you want this behavior as default or maybe introduce this option in your plugin and delegate it to the parser. But that's something to start with ;-)

**Comment by Smasherr** [comment]
Ah, you don't need my PR because you already implemented it. I just oversaw it.

**Comment by agabrys** [comment]
@Smasherr I fixed `StylePropertyConverter` in `feature/#26` branch. You modified code located in `develop` branch. That is the reason why you had to fix `StylePropertyConverter` on your own. I see that you use `CSSFormat` in more classes. I'm verifying where the change is needed (e.g. `CharsetRuleConverter` does not require any changes, because `CSSCharsetRuleImpl#getCssText(CssFormat)` does not use the `format` parameter).

**Comment by Smasherr** [comment]
> I'm verifying where the change is needed
Well I was sure you'll verify it :+1:
Another tiny difference is that I cast to `CSSFormatable` instead of `CSSValueImpl` in `StylePropertyConverter`, which is maybe more safe?

**Comment by agabrys** [comment]
I checked and we also should use `CSSFormat` in:
* `ImportRuleConverter`
* `MediaRuleConverter`
* `UnknownRuleConverter`
* `UnsupportedRuleException`

I'll push new code next 30 minutes.

**Comment by agabrys** [comment]
I pushed final solution. If you have some free time - please check the code. Tomorrow I'll merge it to `develop` and next release a new version: `2.0.0`.

**Comment by Smasherr** [comment]
@agabrys Looks good to me, nice work!

**Comment by agabrys** [comment]
@Smasherr cool, thanks 👍 I'll release it today's evening.

**Comment by Smasherr** [comment]
@agabrys This is great, because I can remove our workaround for #23 and #26 tomorrow at the office and see how our stylesheets look with the new plugin version. I will give you my feedback once again after that.

**Comment by Smasherr** [comment]
@agabrys I tested the fixes and can say the plugin works like a charm! I compared our original css with the splitted and saw that both important properties as well as escaped strings are still in place. I noticed some minor differences, but I don't know if they are worth opening an issue for them:
- `#fff` is converted to `rgb(255, 255, 255)`
- `.base [draggable=true]` is converted to `.base [draggable="true"]`
- `line-height: 25px;/**blablabla**/` is converted to `line-height: 25px;`
They are not critical so you decide if you want to have them fixed ;-)

**Comment by agabrys** [comment]
Thank you for verification 👍

> `#fff` is converted to `rgb(255, 255, 255)`

I have only two options provided by the CSS Parser, print always:
1. hex code with 6 letters: `#fff` → `#ffffff` and `rgb(255, 255, 255)` → `#ffffff`
1. rgb function: `#fff` → `rgb(255, 255, 255)`

I think that `#ffffff` is more concise and readable than `rgb(255, 255, 255)` so a new ticket for it is a good idea.

> `.base [draggable=true]` is converted to` .base [draggable="true"]`

I cannot fix it without some changes in CSS Parser. Luckily those two attribute selectors are equivalent, so the change won't break anything. I think there is a very low chance that CSS Parser will be changed in this area (they have much more important issues to fix).

 > `line-height: 25px;/**blablabla**/` is converted to `line-height: 25px;`

CSS Parser removes all comments. To change this behavior CSS Parser has to be rewritten or I have to find another parser. Let's say it is impossible right now ;)
