### ISSUE TITLE
Cannot parse css

### ISSUE THREAD

**Issue by ij11** [gabrysbiz/css-splitter-maven-plugin#3]
I wanted to use the plugin on a vaadin project to split my large css file for IE9 support.

My stylesheet contains the vaadin base.scss and one of their styles cannot be parsed, so i have no chance to correct it.

My build fails with : Cannot parse CSS code, reason: unsupported character (character number: 41): fore {
[ERROR] content: url(data:image/svg+xml;charset=utf-8;base64,PHN2ZyB4bWxucz0iaHR

The selector in the stylesheet is:
.ie8 .base .v-grid-cell-focused:before, .ie9 .base .v-grid-cell-focused:before, .ie10 .base .v-grid-cell-focused:before {
	content: url(data:image/svg+xml;charset=utf-8;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciPjwvc3ZnPg==);
}

**Comment by agabrys** [comment]
If you use `url(data...);` then please add them in single (`url('data...');`) or double (`url("data...");`) quotes.

This plugin is still under development and now is very unstable. Sometimes some parts of source code are missing in generated file. I will try to repair it on this weekend.

**Comment by ij11** [comment]
Ok thank you very much! ;)

Unfortunately I cannot change this because i only import this existing external vaadin stylesheet.
A fix for this would be great.
Thanks.

**Comment by agabrys** [comment]
Ok, I will try.

**Comment by agabrys** [comment]
I will change core from "my own" to [CSS Parser](http://cssparser.sourceforge.net/). I think this should solve the problem. I hope that first version with new core will be available before first march 2016.

**Comment by ij11** [comment]
Thanks, is it already changed? I still got the same problem ;(

**Comment by agabrys** [comment]
I still work on it. Probably I will upload a new snapshot today.

**Comment by agabrys** [comment]
Today I added more validation and started to create a mechanism that cuts the stylesheet tree. Tomorrow I will back to work.

**Comment by agabrys** [comment]
I uploaded a new snapshot with first working draft. You can test it :-)

I still have to:
* add tests
* break execution if CSS is invalid
* do some refactor
* add parameter to set maximum imports per file
* etc.
But if your CSS is correct, then you should not have more problem :-) Thank you for you feedback.

**Comment by agabrys** [comment]
If you have any problems with new version - please write feedback quickly, because I will be very busy from 12th March to 20th March (I can correct something before 12th or after 20th).

**Comment by ij11** [comment]
Thanks for the fix. My origin problem is solved with the new version, now i have an other issue on compilation ;)
```
null [8601:2] Fehler in Style-Regel. (Ungültiger Token "@font-face". Erwartet wurde einer von: <EOF>, <S>, <IDENT>, "}", ";", "*".)
null [8601:2] Ignoriere die folgenden Deklarationen in dieser Regel.
null [8608:1] Fehler im Stylesheet. (Ungültiger Token "}". Erwartet wurde einer von: <EOF>, <S>, <IDENT>, "<!--", "-->", ".", ":", "*", "[", <HASH>, <IMPORT_SYM>, <PAGE_SYM>, <MEDIA_SYM>, <FONT_FACE_SYM>, <ATKEYWORD>.)
[INFO] Finished source files split in 0.787 seconds
```
There are some font icons declared in the external vaadin stylesheet like:  
```
@font-face {
	font-family: FontAwesome;
	src: url(../base/fonts/fontawesome-webfont.eot);
	src: url(../base/fonts/fontawesome-webfont.eot?#iefix) format("embedded-opentype"), url(../base/fonts/fontawesome-webfont.woff) format("woff"), url(../base/fonts/fontawesome-webfont.ttf) format("truetype"), url(../base/fonts/fontawesome-webfont.svg) format("svg");
	font-weight: normal;
	font-style: normal;
}
```

The build runs successfully but the css file is not splitted...

**Comment by agabrys** [comment]
I will check it.

**Comment by agabrys** [comment]
I added a test which correctly parse your code example. Are you sure that the line 8601 indicates `@font-face` rule from example.

**Comment by agabrys** [comment]
FYI: I added "break execution if CSS is invalid"

**Comment by ij11** [comment]
Thank you very much. It worked now perfect! ;) The fontface issue was a bug in my scss file.
I wanted to ask if you have planned to make a release from your project in near future?
Because  this would be nicer than working with the snapshot version. 
Thanks in advance!

**Comment by agabrys** [comment]
Yes, I will release plugin after the completion of all tasks from 1.0 milestone.

**Comment by ij11** [comment]
Ok, do you have a round estimated time for this? ;) sorry, for getting on your nerves, but it seems that i am only allowed to use released versions for my project, and your plugin works excellent for me

**Comment by agabrys** [comment]
I hope that I will release it in May/June.
