### ISSUE TITLE
Add support for @rules inside @media rule

### ISSUE THREAD

**Issue by agabrys** [gabrysbiz/css-splitter-maven-plugin#9]
Now plugin throws error when you put @rule inside ``@media`` query, example:

    @media all {
        @page {
            maring: 2px;
        }
    }

This is not a correct CSS code (see [CSS Validation Service](http://jigsaw.w3.org/css-validator/)), but users really want support of this.

This functionality will work as long as [CSS Parser](http://cssparser.sourceforge.net/) will parse incorrect code.

**Comment by agabrys** [comment]
You can enable `NON STRICT` mode by add parameter `<nonstrict>true</nonstrict>`.

**Comment by philipjohn007** [comment]
Cool..

**Comment by agabrys** [comment]
I hope that this solved your problem.
